### ISSUE TITLE
일부 연산 수행 시 스택이 예상 결과와 다르게 처리되는 문제가 있습니다.

### ISSUE THREAD

**Issue by xnuk** [buttercrab/hyeo-ung-lang#36]
## 코드
```
혀이삼사 오육칠엉⋮⋮⋮ 흣. 혀엉⋮ 흐읏. 흑. 흑
```

### 맞는 실행 결과
명령어 | 3번 스택 | 출력
--|--|--
`혀이삼사 오육칠엉⋮⋮⋮` | `72`
`흣.` | `-72` | `72` (-72)
`혀엉⋮` | `-72, 6`
`흐읏.` | `72, -6`  | `B` (66)
`흑.` | `72, -6`  | `6` (-6)
`흑` | `72, -6`

출력: `72B6`

### 실제 실행 결과
```
$ yes 'state
next' | cargo run debug foo.hyeong

> current stack: 3
> 0 | foo.hyeong:1:0  혀이삼사오육칠엉⋮⋮⋮
> current stack: 3
stack 3: [72]
> 1 | foo.hyeong:2:0  흣.
[stdout] 72
> current stack: 3
stack 3: [-72]
> 2 | foo.hyeong:3:0  혀엉⋮
> current stack: 3
stack 3: [-72, 6]
> 3 | foo.hyeong:4:0  흐읏.
[stdout] B
> current stack: 3
stack 3: [-6, 72]
> 4 | foo.hyeong:5:0  흑.
[stdout] H
> current stack: 1
stack 3: [-6, 72]
> 5 | foo.hyeong:6:0  흑
```

출력: `72BH`

## 그외
`형흑......흡.혀어엉...흐읏.흐윽.흑`의 실행 결과가 맞게 나오지 않습니다. (expect: `너무 커엇...너무 커엇...99` / actual: `너무 커엇...너무 커엇...너무 커엇...너무 커엇...`)

**Comment by buttercrab** [comment]
`흣` 명령어가 잘못 쓰여진 것 같습니다. 버그 찾아주셔서 감사합니다!

**Comment by buttercrab** [comment]
@xnuk [Version 0.2.2](https://github.com/buttercrab/hyeo-ung-lang/releases/tag/v0.2.2)에서 버그를 고쳤습니다 :)
